[package]
name = "rsdic"
version = "0.1.0"
authors = ["Ji-Hun Kim <jihuun.k@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.3", features = ["blocking"] }
select = "0.5.0"
